// Generated by `supabase gen types typescript` (via the Supabase MCP connector).
// Do NOT edit by hand. Regenerate after any schema change and commit the result.
// See agent-orchestration/dev-guide.md § Type discipline.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      bulletins: {
        Row: {
          created_at: string
          display_end: string | null
          display_start: string
          id: string
          message: string
          published: boolean
          title: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          display_end?: string | null
          display_start?: string
          id?: string
          message: string
          published?: boolean
          title?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          display_end?: string | null
          display_start?: string
          id?: string
          message?: string
          published?: boolean
          title?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      classes: {
        Row: {
          category: Database["public"]["Enums"]["class_category"]
          created_at: string
          description: string
          fee_notes: string | null
          id: string
          image_alt: string | null
          image_url: string | null
          kit_fee: number | null
          max_students: number | null
          name: string
          prerequisite: string | null
          published: boolean
          skill_level: Database["public"]["Enums"]["skill_level"]
          slug: string
          supply_fee: number | null
          tuition: number
          updated_at: string
        }
        Insert: {
          category: Database["public"]["Enums"]["class_category"]
          created_at?: string
          description: string
          fee_notes?: string | null
          id?: string
          image_alt?: string | null
          image_url?: string | null
          kit_fee?: number | null
          max_students?: number | null
          name: string
          prerequisite?: string | null
          published?: boolean
          skill_level: Database["public"]["Enums"]["skill_level"]
          slug: string
          supply_fee?: number | null
          tuition: number
          updated_at?: string
        }
        Update: {
          category?: Database["public"]["Enums"]["class_category"]
          created_at?: string
          description?: string
          fee_notes?: string | null
          id?: string
          image_alt?: string | null
          image_url?: string | null
          kit_fee?: number | null
          max_students?: number | null
          name?: string
          prerequisite?: string | null
          published?: boolean
          skill_level?: Database["public"]["Enums"]["skill_level"]
          slug?: string
          supply_fee?: number | null
          tuition?: number
          updated_at?: string
        }
        Relationships: []
      }
      cohort_sessions: {
        Row: {
          cohort_id: string
          created_at: string
          ends_at: string
          gcal_event_id: string | null
          id: string
          starts_at: string
          sync_error: string | null
          sync_status: string
          updated_at: string
        }
        Insert: {
          cohort_id: string
          created_at?: string
          ends_at: string
          gcal_event_id?: string | null
          id?: string
          starts_at: string
          sync_error?: string | null
          sync_status?: string
          updated_at?: string
        }
        Update: {
          cohort_id?: string
          created_at?: string
          ends_at?: string
          gcal_event_id?: string | null
          id?: string
          starts_at?: string
          sync_error?: string | null
          sync_status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "cohort_sessions_cohort_id_fkey"
            columns: ["cohort_id"]
            isOneToOne: false
            referencedRelation: "cohorts"
            referencedColumns: ["id"]
          },
        ]
      }
      cohorts: {
        Row: {
          class_id: string
          created_at: string
          enrollment_count: number | null
          id: string
          kind: Database["public"]["Enums"]["cohort_kind"]
          label: string | null
          published: boolean
          updated_at: string
        }
        Insert: {
          class_id: string
          created_at?: string
          enrollment_count?: number | null
          id?: string
          kind: Database["public"]["Enums"]["cohort_kind"]
          label?: string | null
          published?: boolean
          updated_at?: string
        }
        Update: {
          class_id?: string
          created_at?: string
          enrollment_count?: number | null
          id?: string
          kind?: Database["public"]["Enums"]["cohort_kind"]
          label?: string | null
          published?: boolean
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "cohorts_class_id_fkey"
            columns: ["class_id"]
            isOneToOne: false
            referencedRelation: "classes"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      class_category: "stained_glass" | "mosaic" | "fused_glass" | "other"
      cohort_kind: "multi_session" | "single_session"
      skill_level: "beginner" | "intermediate" | "advanced" | "all_levels"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      class_category: ["stained_glass", "mosaic", "fused_glass", "other"],
      cohort_kind: ["multi_session", "single_session"],
      skill_level: ["beginner", "intermediate", "advanced", "all_levels"],
    },
  },
} as const
