// Walks each agent-orchestration/phase-*/tasks/ directory, reads task
// frontmatter, and regenerates the `<!-- generated -->` tracker table inside
// the corresponding phase-*/README.md. Idempotent — safe to re-run.
//
// Run from the repo root:
//   pnpm gen:tracker
//
// Required env: none. This script is pure filesystem.

import { readdir, readFile, writeFile, stat } from "node:fs/promises";
import { join, basename } from "node:path";

const ROOT = process.cwd();
const ORCH_DIR = join(ROOT, "agent-orchestration");
const MARKER_START =
  "<!-- generated by `pnpm gen:tracker`; do not edit manually -->";
const MARKER_END = "<!-- end generated -->";

function parseFrontmatter(source) {
  const match = source.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return null;
  const result = {};
  for (const line of match[1].split("\n")) {
    const m = line.match(/^([a-zA-Z_]+):\s*(.*)$/);
    if (!m) continue;
    const [, key, raw] = m;
    let value = raw.trim();
    if (value.startsWith("[") && value.endsWith("]")) {
      value = value
        .slice(1, -1)
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean);
    }
    result[key] = value;
  }
  return result;
}

function buildTable(tasks) {
  const header =
    "| ID | Title | Status | Depends on |\n| -- | ----- | ------ | ---------- |";
  if (tasks.length === 0) {
    return `${header}\n| _no tasks yet_ | | | |`;
  }
  const rows = tasks.map((t) => {
    const deps =
      Array.isArray(t.depends_on) && t.depends_on.length > 0
        ? t.depends_on.join(", ")
        : "—";
    return `| ${t.id} | ${t.title} | ${t.status} | ${deps} |`;
  });
  return [header, ...rows].join("\n");
}

async function regenPhase(phaseDir) {
  const phaseName = basename(phaseDir);
  const readmePath = join(phaseDir, "README.md");
  let readme;
  try {
    readme = await readFile(readmePath, "utf8");
  } catch {
    console.warn(`skipping ${phaseName}: no README.md`);
    return;
  }

  const tasksDir = join(phaseDir, "tasks");
  let taskFiles = [];
  try {
    taskFiles = (await readdir(tasksDir))
      .filter((f) => f.endsWith(".md"))
      .sort();
  } catch {
    // no tasks/ subdir — treat as empty
  }

  const tasks = [];
  for (const f of taskFiles) {
    const source = await readFile(join(tasksDir, f), "utf8");
    const fm = parseFrontmatter(source);
    if (!fm) {
      console.warn(`  ${phaseName}/tasks/${f}: no frontmatter; skipped`);
      continue;
    }
    if (!fm.id || !fm.title || !fm.status) {
      console.warn(
        `  ${phaseName}/tasks/${f}: missing id/title/status; skipped`,
      );
      continue;
    }
    tasks.push(fm);
  }

  const startIdx = readme.indexOf(MARKER_START);
  const endIdx = readme.indexOf(MARKER_END);
  if (startIdx === -1 || endIdx === -1) {
    console.warn(`  ${phaseName}/README.md: tracker markers not found; skipped`);
    return;
  }
  const before = readme.slice(0, startIdx + MARKER_START.length);
  const after = readme.slice(endIdx);
  const updated = `${before}\n\n${buildTable(tasks)}\n\n${after}`;

  if (updated === readme) {
    console.log(`= ${phaseName}: no changes (${tasks.length} task(s))`);
    return;
  }

  await writeFile(readmePath, updated);
  console.log(`✓ ${phaseName}: regenerated (${tasks.length} task(s))`);
}

async function main() {
  let entries;
  try {
    entries = await readdir(ORCH_DIR);
  } catch {
    console.error(`agent-orchestration/ not found at ${ORCH_DIR}`);
    process.exit(1);
  }

  const phaseDirs = [];
  for (const name of entries) {
    if (!name.startsWith("phase-")) continue;
    const full = join(ORCH_DIR, name);
    const st = await stat(full);
    if (st.isDirectory()) phaseDirs.push(full);
  }
  phaseDirs.sort();

  if (phaseDirs.length === 0) {
    console.warn(`no phase directories found in ${ORCH_DIR}`);
    return;
  }

  for (const phaseDir of phaseDirs) {
    await regenPhase(phaseDir);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
